@include('frontend.head.header')
@include('frontend.head.menu_pc')
@include('frontend.body.slide')
@include('frontend.body.service')
@include('frontend.body.work_flow')
@include('frontend.body.portfolio')
@include('frontend.body.industrie')
@include('frontend.body.competence')
{{-- @include('frontend.body.avis') --}}
@include('frontend.body.about_me')
@include('frontend.body.contact')
@include('frontend.footer.footer')